### ISSUE TITLE
Full screen button is missing

### ISSUE THREAD

**Issue by writeincodes** [ct7ct7ct7/Android-VimeoPlayer#1]
I am wondering why it does not have an option to toggle fullscreen. Is there any issues with Player.js? (*I am not familiar with JS)

**Comment by ct7ct7ct7** [comment]
I didn't change vimeo player.js default setting.I think there is not for mobile customize control bar.

**Comment by ct7ct7ct7** [comment]
I think I can make it for the future.

**Comment by arunjish** [comment]
please enable the full-screen button. if possible.

**Comment by ct7ct7ct7** [comment]
Update version to 1.0.5 and set attributes ...
`app:showOriginalControls="false"
`
`
app:showFullscreenOption="true"
`


[https://github.com/ct7ct7ct7/Android-VimeoPlayer#fullscreen-options](url)

**Comment by muhammedfayazp** [comment]
video width is short. please fix that too

**Comment by muhammedfayazp** [comment]
@ct7ct7ct7 sorry, it was issue in my video

**Comment by ct7ct7ct7** [comment]
@muhammedfayazp about the view width, fixed on the v1.0.7
