### ISSUE TITLE
What exactly is "SettingsEmbeddedUrl"?

### ISSUE THREAD

**Issue by minhnbwork97** [ct7ct7ct7/Android-VimeoPlayer#17]
Hi. Thank you for making such a great library, I am currently using it for streaming my domain restricted Vimeo video, but I am struggling with this "SettingsEmbeddedUrl" thing. Can you give us more information about "SettingsEmbeddedUrl", like a tutorial video about how to get "SettingsEmbeddedUrl" on your Vimeo account or just a list of steps to tell us how to get "SettingsEmbeddedUrl"?

**Comment by DevToDipesh** [comment]
Hi @minhnbwork97 Did u get solution ?

I have some private videos but i am stuck how to get hashkey and this SettingEmbeddedUrl
Please reply for the same

**Comment by minhnbwork97** [comment]
@DevToDipesh 
I don't remember exactly, you may have to dig a little bit more :D.
- Hashkey: you can find it via Vimeo API https://developer.vimeo.com/api/reference
- SettingEmbeddedUrl: it's in your video settings 
![image](https://user-images.githubusercontent.com/38205529/76391907-13217400-63a3-11ea-831b-eb1d78c9343e.png)

Hope this helps!
