### ISSUE TITLE
Video is not playing when I am using it inside a recyclerview

### ISSUE THREAD

**Issue by Nidhinkmadhu** [ct7ct7ct7/Android-VimeoPlayer#6]
I tried using it inside a recyclerview but only audio is working Video is not being played .
audio is played even if device is locked

**Comment by ct7ct7ct7** [comment]
Hey friend, Refer to the following this.

**Comment by Nidhinkmadhu** [comment]
Hi friend,
When i tried using this library inside a sample app it was working very
well but when i tried to integrate it to my original app this problem
arises . ie I could hear only audio of the file . Instead of the video part
a white background is visible .. please help me


Thanks

**Comment by ct7ct7ct7** [comment]
@Nidhinkmadhu Can you provide any screenshot?

**Comment by Nidhinkmadhu** [comment]
Hey Friend I have attached a Screenshot as well as a gif image along with this comment  please check it

image
![vimeo](https://user-images.githubusercontent.com/22489651/53569512-6656c900-3b8a-11e9-87a3-0beb2bcc422d.png)

gif
![vimeo](https://user-images.githubusercontent.com/22489651/53570106-b84c1e80-3b8b-11e9-9413-c8771e19a6fc.gif)

**Comment by ct7ct7ct7** [comment]
Try to the latest version still have this problem?
