### ISSUE TITLE
video not playing in full screen in landscape (google pixel 2 xl)

### ISSUE THREAD

**Issue by sunilkumarmaurya** [ct7ct7ct7/Android-VimeoPlayer#7]
video not playing in full screen in google pixel 2 xl  landscape mode.Frame is full screen showing But Video not showing  full screen. Screen Resolution(1920×1080)

![Screenshot_1552455986](https://user-images.githubusercontent.com/5163612/54256399-e402d780-4581-11e9-9a1b-1e43099f2948.png)

**Comment by ct7ct7ct7** [comment]
I think this bug fixed on the version 1.1.2
