### ISSUE TITLE
Black Screen

### ISSUE THREAD

**Issue by oguzzhan** [ct7ct7ct7/Android-VimeoPlayer#8]
The video is loading i can see the title but at first i can't see the thumbnail image. When i tap the play button it plays and i can see the video. Thank you.

**Comment by oguzzhan** [comment]
it's because of i set the "showOriginalControls : false". When it's true i can see the thumbnail image.

**Comment by ct7ct7ct7** [comment]
Do you know how to get the vimeo video thumbnail?
maybe I should add it to the first.

**Comment by oguzzhan** [comment]
It's an API that written by my company.

**Comment by ct7ct7ct7** [comment]
Support the thumbnail at v1.1.5 👍
