### ISSUE TITLE
Video fullScrenn on screen rotation

### ISSUE THREAD

**Issue by YogeshTripathi5** [ct7ct7ct7/Android-VimeoPlayer#9]
Video not playing full screen on screen rotation.
aspect ration app:aspectRatio="1.778"

**Comment by ct7ct7ct7** [comment]
You should do that by yourself.
https://github.com/ct7ct7ct7/Android-VimeoPlayer#fullscreen-options

**Comment by YogeshTripathi5** [comment]
i implemented in java and found that setFullscreenClickListener not getting called

    vimeoPlayer.initialize(Integer.parseInt(getIntent().getStringExtra("url")));
        vimeoPlayer.setFullscreenVisibility(true);

        vimeoPlayer.setFullscreenClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {


                String requestOrientation = VimeoPlayerActivity.REQUEST_ORIENTATION_AUTO;

                startActivityForResult(VimeoPlayerActivity.createIntent(VimeoActivity.this, requestOrientation, vimeoPlayer), REQUEST_CODE);

            }
        });


        vimeoPlayer.play();


    @Override
    protected void onActivityResult(int requestCode, int resultCode, @Nullable Intent data) {
        super.onActivityResult(requestCode, resultCode, data);

        if (resultCode == VimeoActivity.RESULT_OK && requestCode == REQUEST_CODE) {
            float playAt = data.getFloatExtra(VimeoPlayerActivity.RESULT_STATE_VIDEO_PLAY_AT, 0f);
            vimeoPlayer.seekTo(playAt);

            PlayerState playerState = PlayerState.valueOf(data.getStringExtra(VimeoPlayerActivity.RESULT_STATE_PLAYER_STATE));
            switch (playerState) {
                case PLAYING:
                    vimeoPlayer.play();
                    break;
                case PAUSED:
                    vimeoPlayer.pause();
                    break;
                case ENDED:
                    vimeoPlayer.reset();
                    break;
            }
        }
    }

**Comment by ct7ct7ct7** [comment]
I have testing at my other project and it's working. [Follow ](https://github.com/ct7ct7ct7/Android-VimeoPlayer/blob/master/sample/src/main/java/com/ct7ct7ct7/androidvimeoplayersample/examples/FullscreenActivity.kt)

**Comment by YogeshTripathi5** [comment]
can u send me your manifest and that class in which you have used this code?

**Comment by ct7ct7ct7** [comment]
Follow this [example](https://github.com/ct7ct7ct7/VimeoTest)

**Comment by YogeshTripathi5** [comment]
worked thanks...u r awesome :)
